
<h3>Pessoas Cadastradas</h3>

<a class=" btn btn-primary" href="<?= $this->url('pessoa', ['controller' => 'pessoa', 'action' => 'adicionar']) ?>">Adicionar</a>
<table class='table table-striped'>
    <tr>
        <th>Código</th>
        <th>Nome</th>
        <th>Sobrenome</th>
        <th>Email</th>
        <th>Sistuação</th>
        <th>Ação</th>
    </tr>
<?php foreach($pessoas as $pes){  ?>
    <tr>
        <td>
            <?=$pes->getId()?>
        </td>
        <td>
            <?=$pes->getNome()?>
        </td>
        <td>
            <?=$pes->getSobrenome()?>
        </td>
        <td>
            <?=$pes->getEmail()?>
        </td>
        <td>
            <?=$pes->getSituacao()?>
        </td>
        <td>
            <a class='btn-info btn btn-sm' href="<?= $this->url('pessoa', ['action' => 'editar', 'id' => $pes->getId()]) ?>">Editar</a>

            <a class='btn-danger btn btn-sm' href="<?= $this->url('pessoa', ['action' => 'remover', 'id' => $pes->getId()]) ?>">Excluir</a>
        </td>
        
    </tr>
<?php } ?>
</table>