<?php
    $title = "Removendo Pessoa";

    $this->headTitle($title);


?>
<h1><?=$this->escapeHtml($title)?></h1>
<?php

//$form->setAttribute('action', $this->url('pessoa', ['action'=>remover]));
?>
<p>Você deseja excluir <?=$this->escapeHtml($pessoa->getNome())?>?</p>

<form method='POST' action="<?=$this->url('pessoa', ['action' => 'remover', 'id' => $id])?>">
    <div class="form-group">
        <input type="hidden" name="id" value="<?=$id?>">
        <input type="submit" class="btn btn-danger" name="del" value="sim">
        <input type="submit" class="btn btn-success" name="del" value="nao">
    </div>
</form>
